# Generated by Django 3.0.7 on 2020-06-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('rang_affichage', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos')),
                ('etat', models.CharField(choices=[('pub', 'Publié'), ('not_pub', 'Non publié')], max_length=255)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organigramme.Fonction')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organigramme.Grade')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organigramme.Pole')),
            ],
        ),
    ]
