# Generated by Django 3.0.7 on 2020-06-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='fonction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Fonction'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Grade'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='pole',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Pole'),
        ),
    ]
