# Generated by Django 3.0.7 on 2020-06-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0003_auto_20200618_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Fonction'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Grade'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Pole'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
