# Generated by Django 3.0.7 on 2020-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0004_auto_20200618_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
