# Generated by Django 3.0.7 on 2020-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0006_fiche_nombre_elements_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='nombre_elements_ligne',
            field=models.CharField(choices=[('col-4', '1/3'), ('col-6', '1/2'), ('col-12', '1')], default='col-4', max_length=255),
        ),
    ]
