# Generated by Django 3.0.7 on 2020-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0007_auto_20200619_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='nombre_elements_ligne',
            field=models.CharField(choices=[('col-4', '3'), ('col-6', '2'), ('col-12', '1')], default='col-4', max_length=255),
        ),
    ]
