# Generated by Django 3.0.7 on 2020-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0008_auto_20200619_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.FilePathField(null=True, path='photos'),
        ),
    ]
