# Generated by Django 3.0.7 on 2020-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0012_fonction_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
