# Generated by Django 3.0.7 on 2020-06-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0015_auto_20200625_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organigramme.Groupe'),
        ),
    ]
