# Generated by Django 3.0.7 on 2020-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0016_fiche_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='importance',
            field=models.IntegerField(default=999),
        ),
    ]
